In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('reduced_task_events.csv')

In [3]:
df

,Unnamed: 0,timestamp,job ID,task index,machine ID,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space
0,277322,6.000469e+08,6251537638,1832,4.304052e+09,2,0.02499,0.079590,0.000386
1,277323,6.000469e+08,6251537638,1784,2.887802e+09,2,0.02499,0.079590,0.000386
2,277324,6.000470e+08,6251537638,1890,7.114190e+05,2,0.02499,0.079590,0.000386
3,277325,6.000471e+08,6251537638,1510,7.655360e+05,2,0.02499,0.079590,0.000386
4,277326,6.000472e+08,6251537638,1445,1.436481e+09,2,0.02499,0.079590,0.000386
...,...,...,...,...,...,...,...,...,...
18217908,144647765,2.506196e+12,6486519055,51,3.516642e+08,4,0.03125,0.009323,0.000154
18217909,144647766,2.506196e+12,6486519055,89,4.820185e+09,4,0.03125,0.009323,0.000154
18217910,144647768,2.506197e+12,6486519055,88,4.820018e+09,4,0.03125,0.009323,0.000154
18217911,144647777,2.506198e+12,6486611683,0,2.847381e+08,8,0.03125,0.007950,0.000038
18217912,144647778,2.506198e+12,6486161686,925,3.360744e+08,6,0.03687,0.019900,0.000771

In [4]:
nan_df = df[(df['resource request for CPU cores'] > 0) &
            (df['resource request for RAM'] > 0) &
            (df['resource request for local disk space'] > 0)]

In [5]:
grouped_df = nan_df.groupby(['job ID', 'priority', 'resource request for CPU cores', 'resource request for RAM', 
                             'resource request for local disk space'], as_index=False).size().reset_index(name='Count')

In [6]:
grouped_df

,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space,Count
0,0,0.000625,0.003109,0.000015,2449
1,0,0.000625,0.003109,0.000031,2264
2,0,0.000625,0.005486,0.000038,462
3,0,0.000625,0.006104,0.000038,51
4,0,0.000625,0.006569,0.000115,2
...,...,...,...,...,...
15163,9,0.093750,0.238800,0.000771,9
15164,9,0.156200,0.159200,0.000386,2
15165,9,0.250000,0.122800,0.000579,11
15166,9,0.375000,0.477500,0.009644,1
15167,9,0.375000,0.636700,0.009644,3

In [7]:
grouped_df.sort_values(by='Count', ascending=False)

,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space,Count
12530,4,0.062500,0.031800,0.000771,1044520
10516,4,0.024990,0.033390,0.000386,1043895
10510,4,0.024990,0.025450,0.000386,817372
5470,2,0.006248,0.007767,0.000032,352535
4793,1,0.012500,0.031800,0.000154,351445
...,...,...,...,...,...
1896,0,0.012150,0.019410,0.000010,1
10267,4,0.024990,0.009720,0.000386,1
1899,0,0.012160,0.002579,0.000038,1
12179,4,0.049990,0.019100,0.000019,1
13600,4,0.087400,0.002190,0.000038,1

In [8]:
top_df = grouped_df[grouped_df['Count'] >= 1000]

In [9]:
top_df

,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space,Count
0,0,0.000625,0.003109,0.000015,2449
1,0,0.000625,0.003109,0.000031,2264
20,0,0.001249,0.015530,0.000038,5515
21,0,0.001249,0.015900,0.000038,2848
26,0,0.001249,0.023320,0.000038,7070
...,...,...,...,...,...
15124,9,0.012500,0.007767,0.000027,4903
15134,9,0.046880,0.063600,0.000038,2964
15137,9,0.062500,0.002331,0.000004,1909
15138,9,0.062500,0.015900,0.000004,2947
15142,9,0.062500,0.031800,0.000038,2624

In [10]:
total = top_df['Count'].sum()
total

16223703

In [11]:
prob_df = top_df
prob_df['Probablity'] = prob_df['Count'].apply(lambda count: count / total)
prob_df

c:\users\mark\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space,Count,Probablity
0,0,0.000625,0.003109,0.000015,2449,0.000151
1,0,0.000625,0.003109,0.000031,2264,0.000140
20,0,0.001249,0.015530,0.000038,5515,0.000340
21,0,0.001249,0.015900,0.000038,2848,0.000176
26,0,0.001249,0.023320,0.000038,7070,0.000436
...,...,...,...,...,...,...
15124,9,0.012500,0.007767,0.000027,4903,0.000302
15134,9,0.046880,0.063600,0.000038,2964,0.000183
15137,9,0.062500,0.002331,0.000004,1909,0.000118
15138,9,0.062500,0.015900,0.000004,2947,0.000182
15142,9,0.062500,0.031800,0.000038,2624,0.000162

In [12]:
min_cpu_core = prob_df['resource request for CPU cores'].min()
min_cpu_core

0.0006247000000000001

In [13]:
min_ram = prob_df['resource request for RAM'].min()
min_ram

0.0001554

In [14]:
min_disk_space = prob_df['resource request for local disk space'].min()
min_disk_space

9.537e-07

In [16]:
normalised_df = prob_df
normalised_df['normalised CPU cores'] = prob_df['resource request for CPU cores'].apply(lambda cpu_core: cpu_core / min_cpu_core)
normalised_df['normalised RAM'] = prob_df['resource request for RAM'].apply(lambda ram: ram / min_ram)
normalised_df['normalised Disk Space'] = prob_df['resource request for local disk space'].apply(lambda disk_space: disk_space / min_disk_space)
normalised_df

c:\users\mark\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\users\mark\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\mark\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,priority,resource request for CPU cores,resource request for RAM,resource request for local disk space,Count,Probablity,normalised CPU cores,normalised RAM,normalised Disk Space
0,0,0.000625,0.003109,0.000015,2449,0.000151,1.000000,20.006435,16.000839
1,0,0.000625,0.003109,0.000031,2264,0.000140,1.000000,20.006435,32.001678
20,0,0.001249,0.015530,0.000038,5515,0.000340,1.999360,99.935650,40.002097
21,0,0.001249,0.015900,0.000038,2848,0.000176,1.999360,102.316602,40.002097
26,0,0.001249,0.023320,0.000038,7070,0.000436,1.999360,150.064350,40.002097
...,...,...,...,...,...,...,...,...,...
15124,9,0.012500,0.007767,0.000027,4903,0.000302,20.009605,49.980695,27.996225
15134,9,0.046880,0.063600,0.000038,2964,0.000183,75.044021,409.266409,40.002097
15137,9,0.062500,0.002331,0.000004,1909,0.000118,100.048023,15.000000,4.000210
15138,9,0.062500,0.015900,0.000004,2947,0.000182,100.048023,102.316602,4.000210
15142,9,0.062500,0.031800,0.000038,2624,0.000162,100.048023,204.633205,40.002097

In [17]:
normalised_df.to_csv("normalised_task_events.csv", index=False)